### ISSUE TITLE
Default to the snapshot slug naming strat

### ISSUE THREAD

**Issue by d0ugal** [d0ugal/hassio-dropbox-upload#37]

**Comment by adrianmihalko** [comment]
Thanks for the patch.

I experience little problem (if we can call this a problem): if you make multiple backups on the same day, file name will be same and this uploader always try to rewrite the file.

<img width="1027" alt="screenshot 2018-11-14 at 23 15 51" src="https://user-images.githubusercontent.com/733361/48516273-41507b80-e863-11e8-8e43-06527955f795.png">


Log:
https://pastebin.com/HVzUJctC

I would suggest to use file names if file exists:

```
Automated Backup 2018-11-14.tar
Automated Backup 2018-11-14 (2).tar
Automated Backup 2018-11-14 (3).tar
...
```

**Comment by d0ugal** [comment]
Darn. I thought I’d this then forgot about it. I’ll see what I can do.

I’d recommend adding the time to the snapshot name.

**Comment by adrianmihalko** [comment]
+1 for time

**Comment by d0ugal** [comment]
I mean that you should add the time to the snapshot name. It looks like you use a automation similar to the one in the README. If you change it to look like this, it will include the time.

```
  - alias: Backup Nightly
    trigger:
      platform: time
      at: '02:00:00'
    action:
      - service: hassio.snapshot_full
        data_template:
          name: Automated Backup {{ now().strftime('%Y-%m-%d %H-%M-%S') }}
          password: !secret snapshot_password
```
